name: Webdriver testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio
        - name: Upload Results
          uses: actions/upload-artifact@v3
          if: failure()
          with:
            name: allure-result
            path: ./allure-result
